// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xznejbilvqezehmtjffd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh6bmVqYmlsdnFlemVobXRqZmZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzOTIwMDksImV4cCI6MjA2NTk2ODAwOX0.jLggDrS8uH3vugN6ULa6Wl8cwEaF7bwk_RgBX_jd7gk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);